export interface Booking {
  "reserva_id": string,
  "tipo_camion_id": string,
  "tipo_material1_id": string,
  "tipo_material2_id": string,
  "proveedor_id": string,
  "transporte_id": string,
  "muelle1_id": string,
  "muelle2_id": string,
  "status_id": string,
  "empresa_id": string,
  "cantidad1": string,
  "cantidad2": string,
  "pedido_LF ": string,
  "matricula_camion": string,
  "inicio1": string,
  "fin1": string,
  "inicio2": string,
  "fin2": string,
  "es_aduana": string,
  "notas": string,
  "tel1": string,
  "duracion1": string,
  "duracion2": string
}
